# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /icon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /icon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /icon/CMakeFiles /icon//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /icon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named proto-objlib

# Build rule for target.
proto-objlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 proto-objlib
.PHONY : proto-objlib

# fast build rule for target.
proto-objlib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto-objlib.dir/build.make CMakeFiles/proto-objlib.dir/build
.PHONY : proto-objlib/fast

#=============================================================================
# Target rules for targets named objlib

# Build rule for target.
objlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 objlib
.PHONY : objlib

# fast build rule for target.
objlib/fast:
	$(MAKE) $(MAKESILENT) -f icon/CMakeFiles/objlib.dir/build.make icon/CMakeFiles/objlib.dir/build
.PHONY : objlib/fast

#=============================================================================
# Target rules for targets named icon

# Build rule for target.
icon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 icon
.PHONY : icon

# fast build rule for target.
icon/fast:
	$(MAKE) $(MAKESILENT) -f icon/CMakeFiles/icon.dir/build.make icon/CMakeFiles/icon.dir/build
.PHONY : icon/fast

#=============================================================================
# Target rules for targets named icon_unittests

# Build rule for target.
icon_unittests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 icon_unittests
.PHONY : icon_unittests

# fast build rule for target.
icon_unittests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/icon_unittests.dir/build.make tests/CMakeFiles/icon_unittests.dir/build
.PHONY : icon_unittests/fast

#=============================================================================
# Target rules for targets named icon_e2e

# Build rule for target.
icon_e2e: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 icon_e2e
.PHONY : icon_e2e

# fast build rule for target.
icon_e2e/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/icon_e2e.dir/build.make tests/CMakeFiles/icon_e2e.dir/build
.PHONY : icon_e2e/fast

icon/icon/metadata/metadata.pb.o: icon/icon/metadata/metadata.pb.cc.o
.PHONY : icon/icon/metadata/metadata.pb.o

# target to build an object file
icon/icon/metadata/metadata.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto-objlib.dir/build.make CMakeFiles/proto-objlib.dir/icon/icon/metadata/metadata.pb.cc.o
.PHONY : icon/icon/metadata/metadata.pb.cc.o

icon/icon/metadata/metadata.pb.i: icon/icon/metadata/metadata.pb.cc.i
.PHONY : icon/icon/metadata/metadata.pb.i

# target to preprocess a source file
icon/icon/metadata/metadata.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto-objlib.dir/build.make CMakeFiles/proto-objlib.dir/icon/icon/metadata/metadata.pb.cc.i
.PHONY : icon/icon/metadata/metadata.pb.cc.i

icon/icon/metadata/metadata.pb.s: icon/icon/metadata/metadata.pb.cc.s
.PHONY : icon/icon/metadata/metadata.pb.s

# target to generate assembly for a file
icon/icon/metadata/metadata.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto-objlib.dir/build.make CMakeFiles/proto-objlib.dir/icon/icon/metadata/metadata.pb.cc.s
.PHONY : icon/icon/metadata/metadata.pb.cc.s

icon/icon/protobuf/icon.pb.o: icon/icon/protobuf/icon.pb.cc.o
.PHONY : icon/icon/protobuf/icon.pb.o

# target to build an object file
icon/icon/protobuf/icon.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto-objlib.dir/build.make CMakeFiles/proto-objlib.dir/icon/icon/protobuf/icon.pb.cc.o
.PHONY : icon/icon/protobuf/icon.pb.cc.o

icon/icon/protobuf/icon.pb.i: icon/icon/protobuf/icon.pb.cc.i
.PHONY : icon/icon/protobuf/icon.pb.i

# target to preprocess a source file
icon/icon/protobuf/icon.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto-objlib.dir/build.make CMakeFiles/proto-objlib.dir/icon/icon/protobuf/icon.pb.cc.i
.PHONY : icon/icon/protobuf/icon.pb.cc.i

icon/icon/protobuf/icon.pb.s: icon/icon/protobuf/icon.pb.cc.s
.PHONY : icon/icon/protobuf/icon.pb.s

# target to generate assembly for a file
icon/icon/protobuf/icon.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto-objlib.dir/build.make CMakeFiles/proto-objlib.dir/icon/icon/protobuf/icon.pb.cc.s
.PHONY : icon/icon/protobuf/icon.pb.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... icon"
	@echo "... icon_e2e"
	@echo "... icon_unittests"
	@echo "... objlib"
	@echo "... proto-objlib"
	@echo "... icon/icon/metadata/metadata.pb.o"
	@echo "... icon/icon/metadata/metadata.pb.i"
	@echo "... icon/icon/metadata/metadata.pb.s"
	@echo "... icon/icon/protobuf/icon.pb.o"
	@echo "... icon/icon/protobuf/icon.pb.i"
	@echo "... icon/icon/protobuf/icon.pb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

